### PR TITLE
fix: Development package vulnerabilities

### PR DESCRIPTION
**Pull request by jesperronn**
Fixed all critical, high and moderate vulnerabilities for the project. It turned out that there were some major updates, but all were in the dev tools.

Therefore, I would say the update is patch-level, since it mostly affects the building/testing/development of the library

Furthermore, I added a `package-lock.json` to the project

I would say this is best practice in order to be able to deterministically load dependencies on all machines

### CODE REVIEW

**Comment by jesperronn** [comment]
I decided to add a commit here with `package-lock.json`. If you feel strongly about it, I will remove that commit

**Comment by jesperronn** [comment]
@maintainers it seems Travis has a problem with the updated Puppeteer, and I could need help to get this PR green.

From [Puppeteer troubleshooting doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-travis-ci):

>To run headless Chrome on Travis, you must call launch() with flags to disable Chrome's sandbox, like so:
>
> `const browser = await puppeteer.launch({args: ['--no-sandbox']});`


And the error on Travis is:

```
> gavel@0.0.0-semantically-released test:browser /home/travis/build/apiaryio/gavel.js
> mochify "test/unit/**/*.coffee" --transform=coffeeify --extension=.coffee
Error: Failed to launch chrome!
[0613/075659.437639:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x56306038cbac base::debug::StackTrace::StackTrace()
#1 0x56306031aa30 logging::LogMessage::~LogMessage()
#2 0x56306166cce0 service_manager::ZygoteHostImpl::Init()
#3 0x5630600438ad content::ContentMainRunnerImpl::Initialize()
#4 0x56306004c714 service_manager::Main()
#5 0x563060041cc4 content::ContentMain()
#6 0x56306430a389 headless::(anonymous namespace)::RunContentMain()
#7 0x56306430a412 headless::HeadlessBrowserMain()
#8 0x563060049a55 headless::HeadlessShellMain()
#9 0x56305e5d71ac ChromeMain
#10 0x7ff3caedaf45 __libc_start_main
#11 0x56305e5d702a _start
Received signal 6
#0 0x56306038cbac base::debug::StackTrace::StackTrace()
#1 0x56306038c711 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7ff3d0960330 <unknown>
#3 0x7ff3caeefc37 gsignal
#4 0x7ff3caef3028 abort
#5 0x56306038b565 base::debug::BreakDebugger()
#6 0x56306031ae99 logging::LogMessage::~LogMessage()
#7 0x56306166cce0 service_manager::ZygoteHostImpl::Init()
#8 0x5630600438ad content::ContentMainRunnerImpl::Initialize()
#9 0x56306004c714 service_manager::Main()
#10 0x563060041cc4 content::ContentMain()
#11 0x56306430a389 headless::(anonymous namespace)::RunContentMain()
#12 0x56306430a412 headless::HeadlessBrowserMain()
#13 0x563060049a55 headless::HeadlessShellMain()
#14 0x56305e5d71ac ChromeMain
#15 0x7ff3caedaf45 __libc_start_main
#16 0x56305e5d702a _start
  r8: 00007ff3d0f5da00  r9: 00003c54ab5aa800 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffed3bb26e8 r13: 0000000000000161 r14: 00007ffed3bb26f0 r15: 00007ffed3bb26f8
  di: 0000000000000ee7  si: 0000000000000ee7  bp: 00007ffed3bb2230  bx: 00007ffed3bb22a0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007ff3caeefc37  sp: 00007ffed3bb20f8
  ip: 00007ff3caeefc37 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
```

**Comment by honzajavorek** [comment]
Gavel does not use puppeteer directly. It has to be a transitive dependency of one of the dependencies you upgraded. I suggest we do this in multiple steps (multiple PRs):

1. upgrade only the dependencies with vulnerabilities, only to the earliest versions fixing all vulnerabilities
2. upgrade the rest of the dependencies, possibly one by one, which allows us to factor out the problematic ones from the ones which pass the tests at once
3. introducing package-lock.json and reviewing whether package.json and CI setup need any changes as well

What do you think?

**Comment by jesperronn** [comment]
I'm fine with that. Will split PR later today if I can make it 👍

**Comment by honzajavorek** [comment]
Awesome! 🚀 Thank you 🙂

**Pull request closed without merging**
